### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by achafetz** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#2]
check off when you're done QCing or link your issue using the # and then issue number right after your name

Global Workbook Assignments for QC
   - [x] All Global Tabs - Karin, #8, #13, #15, #16, #20, #35, 
   - [x] OU 01: Percent Achievement - Aaron, #4
   - [x] OU 03 Quarterly Trends - Christy
   - [x] OU 04: Quarterly Trend Table - Christy #25 
   - [x] OU 05 Partner Achievement - Aaron, #7
   - [x] OU 06 Partner Comparison - ~~Aaron~~ Gina 
   - [ ] OU 07 Age/Sex Results - Jacob
   - [ ] OU 08 Proportional Age/Sex  - Jacob
   - [x] TX 01 Cascade - Gina
   - [ ] TX 03 Retention Age/Sex - Kristy #28, #29 
   - [x] TX 05 Viral Load Age/Sex - Kristy
   - [x] HTS 01 Volume/Positivity - Jessica
   - [x] HTS 02 Modality - Jessica #18 
   - [x] HTS 03 Positivity by Age/Sex - Anja
   - [x] HTS 04 HTS Pyramids - ~~Anja~~ Nashiva #23 
   - [x] All PMTCT Tabs - Nashiva, #9 #11 
   - [x] KP 01 KP PREV - Maria
   - [x] KP 02 HTS - Maria 
   - [x] KP 03 PrEP - Nashiva
   - [x] KP 04 TX NEW  - Nashiva #27 
   - [x] VMMC 01 Age Bands - Maria #33 
   - [x] VMMC 02 Age Band Trends - Maria 
   - [x] VMMC 03 HIV Testing - Nashiva #31 
   - [x] VMMC 04 Device  - Nashiva #32 

Partner Performance Workbook Assignments for QC 
   - [x] Partner Performance - ~~Aaron~~ Gina  
   - [ ] Age/Sex Performance - Jacob 
   - [x] Index Testing - Jessica, #36 
   - [x] Proxy Linkage  - Jessica

**Comment by AnnaBuschur** [comment]
Could you share with my account as well? I am unable to edit

**Comment by achafetz** [comment]
@AnnaBuschur, sorry, you should be in the group now!

**Comment by mariaau2222** [comment]
Could you share with my account as well?  mariaau2222   I am also unable to edit.  Thank you! :)
